spring.application.name=discografia
spring.data.mongodb.uri=mongodb+srv://karlavergaraiplacex_db_user:1bjWKYzvArGyjL0k@eva-u2-spring.rwyi47w.mongodb.net/discografica-db?retryWrites=true&w=majority
spring.data.mongodb.database=discografica-db